RISK_FREE_RATE = 0.05
PERIOD = "10Y"
BENCHMARK_INDEX = "^GSPC"
INDICATOR = {
    'GDP': 'NY.GDP.MKTP.CD',
    'GDP_GROWTH': 'NY.GDP.MKTP.KD.ZG',
    'GDP_PER_CAPITA': 'NY.GDP.PCAP.CD',
    'GDP_CURRENT_LCU': 'NY.GDP.MKTP.CN',
    'INFLATION': 'FP.CPI.TOTL.ZG',
    'UNEMPLOYMENT': 'SL.UEM.TOTL.ZS',
    'EXPORT': 'NE.EXP.GNFS.CD',
    'IMPORT': 'NE.IMP.GNFS.CD',
    'EXPORT_GROWTH': 'NE.EXP.GNFS.KD.ZG',
    'IMPORT_GROWTH': 'NE.IMP.GNFS.KD.ZG',
    'LABOR_FORCE': 'SL.TLF.TOTL.IN',
    'POPULATION': 'SP.POP.TOTL',
    'EXTERNAL_DEBT': 'DT.DOD.DECT.CD',
    'EXTERNAL_DEBT_GNI': 'DT.DOD.DECT.GN.ZS',
    'HEALTH_EXPENDITURE': 'SH.XPD.CHEX.PC.CD',
    'EDUCATION_EXPENDITURE': 'SE.XPD.TOTL.GB.ZS',
    'ENERGY_USE': 'EG.USE.PCAP.KG.OE'
}
